"""change datatypes boolean for isadmin and isactivate

Revision ID: 598dde99e9f4
Revises: 1fec99fdfb75
Create Date: 2021-11-25 10:03:59.948285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598dde99e9f4'
down_revision = '1fec99fdfb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'isAdmin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               postgresql_using="\"isAdmin\"::boolean")
    op.alter_column('user', 'createdAt',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'isActivate',
               existing_type=sa.INTEGER(),
               server_default='True',
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="\"isActivate\"::boolean")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'isActivate',
               existing_type=sa.Boolean(),
               server_default=None,
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user', 'createdAt',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'isAdmin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
