"""create part-build table

Revision ID: e7ff52db4b2f
Revises: bc62f435455f
Create Date: 2021-11-29 16:00:23.455760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ff52db4b2f'
down_revision = 'bc62f435455f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part__build',
    sa.Column('idPart', sa.Integer(), nullable=False),
    sa.Column('idBuild', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idBuild'], ['build.id'], ),
    sa.ForeignKeyConstraint(['idPart'], ['part.id'], ),
    sa.PrimaryKeyConstraint('idPart', 'idBuild')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part__build')
    # ### end Alembic commands ###
