"""change datatype build

Revision ID: 80a4919cd04a
Revises: 4409d8af4e11
Create Date: 2021-12-02 11:21:12.448412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a4919cd04a'
down_revision = '4409d8af4e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'price',
               existing_type=sa.BOOLEAN(),
               type_=sa.Numeric(),
               existing_nullable=False,
               postgresql_using="\"price\"::bool::int::numeric")
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'price',
               existing_type=sa.Numeric(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
    op.execute("COMMIT")