"""set default value for user createAt col

Revision ID: 1fec99fdfb75
Revises: fa69f2b8d74f
Create Date: 2021-11-23 15:08:25.338981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fec99fdfb75'
down_revision = 'fa69f2b8d74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'createdAt',
               existing_type=sa.DATE(),
               server_default=sa.text('NOW()'),
               existing_nullable=True)
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'createdAt',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
    op.execute("COMMIT")